version: '3'

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    image: rocket/server
    container_name: rocket-server-prod
    networks:
      - app-network
    ports:
      - '80:80'
  client:
    restart: always
    image: rocket/client
    container_name: rocket-client-prod
    volumes:
      - web-root:/var/www/html
    networks:
      - app-network
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'

volumes:
  web-root:

networks:
  app-network:
    driver: bridge